### ISSUE TITLE
Restructure code in integration directory

### ISSUE THREAD

**Issue by bogdandrutu** [census-instrumentation/opencensus-experiments#17]
It is obvious for me as a person who opened this directory that the mix of building systems and languages is hard to understand. I suggest we restructure a bit the code:
* integration/go/grpc/... - contains the go implementation for grpc
* integration/go/http/... - contains the go implementation for http
* integration/java/grpc/... - contains the java implementation for grpc
* integration/java/http/... - contains the java implementation for http
* integration/${LANGUAGE}/${FRAMEWORK}/... - contains the ${LANGUAGE} implementation for ${FRAMEWORK}

**Comment by odeke-em** [comment]
SGTM, thank you @bogdandrutu! We just need to be wary of the fact that the Java code's location dictates where we put the proto definition, /cc @songy23 to help me with the Java restructure.

**Comment by bogdandrutu** [comment]
@odeke-em you can set where the proto files are. See https://github.com/census-instrumentation/opencensus-proto/blob/master/build.gradle#L20

**Comment by songy23** [comment]
That's right, I'm just aware of it and updated the proto path in https://github.com/census-instrumentation/opencensus-experiments/pull/21.
